<form method="post" action="options.php" class='form-group'>



	<?php wp_nonce_field('update-options') ?>



<p><h1 class='title'> A Frame SIGNS | Frame: Frame + Printed Sign(s) | Size:  24" * 36"</h1>


<div class='table-responsive'>

<table class='table table-striped'>

<tr style='text-align:center'>

<td width="100%">Color</td><td>Sign Type</td><td>Printed Side
</td><td>1</td><td>2</td><td>3</td><td>4</td><td>5</td><td>6</td><td>7</td><td>8</td><td>9</td><td>10</td><td>11</td><td>12</td><td>20</td><td>25</td><td>30</td>

</tr>
<tr>
<td>White </td><td>Standard (With Adhesive Signs)</td><td>One Sided</td><td><input type="text" name="aframe_sign_type_1_frame_color1_p_side_1_cost_1"  value="<?php echo get_option('aframe_sign_type_1_frame_color1_p_side_1_cost_1'); ?>" /></td><td><input type="text" name="aframe_sign_type_1_frame_color1_p_side_1_cost_2"  value="<?php echo get_option('aframe_sign_type_1_frame_color1_p_side_1_cost_2'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color1_p_side_1_cost_3"  value="<?php echo get_option('aframe_sign_type_1_frame_color1_p_side_1_cost_3'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color1_p_side_1_cost_4"  value="<?php echo get_option('aframe_sign_type_1_frame_color1_p_side_1_cost_4'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color1_p_side_1_cost_5"  value="<?php echo get_option('aframe_sign_type_1_frame_color1_p_side_1_cost_5'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color1_p_side_1_cost_6"  value="<?php echo get_option('aframe_sign_type_1_frame_color1_p_side_1_cost_6'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color1_p_side_1_cost_7"  value="<?php echo get_option('aframe_sign_type_1_frame_color1_p_side_1_cost_7'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color1_p_side_1_cost_8"  value="<?php echo get_option('aframe_sign_type_1_frame_color1_p_side_1_cost_8'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color1_p_side_1_cost_9"  value="<?php echo get_option('aframe_sign_type_1_frame_color1_p_side_1_cost_9'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color1_p_side_1_cost_10"  value="<?php echo get_option('aframe_sign_type_1_frame_color1_p_side_1_cost_10'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color1_p_side_1_cost_11"  value="<?php echo get_option('aframe_sign_type_1_frame_color1_p_side_1_cost_11'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color1_p_side_1_cost_12"  value="<?php echo get_option('aframe_sign_type_1_frame_color1_p_side_1_cost_12'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color1_p_side_1_cost_20"  value="<?php echo get_option('aframe_sign_type_1_frame_color1_p_side_1_cost_20'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color1_p_side_1_cost_25"  value="<?php echo get_option('aframe_sign_type_1_frame_color1_p_side_1_cost_25'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color1_p_side_1_cost_30"  value="<?php echo get_option('aframe_sign_type_1_frame_color1_p_side_1_cost_30'); ?>"/></td>

</tr>
<tr>
<td>White </td><td>Delux (With Inserted Signs)</td><td>One Sided</td><td><input type="text" name="aframe_sign_type_2_frame_color1_p_side_1_cost_1"  value="<?php echo get_option('aframe_sign_type_2_frame_color1_p_side_1_cost_1'); ?>" /></td><td><input type="text" name="aframe_sign_type_2_frame_color1_p_side_1_cost_2"  value="<?php echo get_option('aframe_sign_type_2_frame_color1_p_side_1_cost_2'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color1_p_side_1_cost_3"  value="<?php echo get_option('aframe_sign_type_2_frame_color1_p_side_1_cost_3'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color1_p_side_1_cost_4"  value="<?php echo get_option('aframe_sign_type_2_frame_color1_p_side_1_cost_4'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color1_p_side_1_cost_5"  value="<?php echo get_option('aframe_sign_type_2_frame_color1_p_side_1_cost_5'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color1_p_side_1_cost_6"  value="<?php echo get_option('aframe_sign_type_2_frame_color1_p_side_1_cost_6'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color1_p_side_1_cost_7"  value="<?php echo get_option('aframe_sign_type_2_frame_color1_p_side_1_cost_7'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color1_p_side_1_cost_8"  value="<?php echo get_option('aframe_sign_type_2_frame_color1_p_side_1_cost_8'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color1_p_side_1_cost_9"  value="<?php echo get_option('aframe_sign_type_2_frame_color1_p_side_1_cost_9'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color1_p_side_1_cost_10"  value="<?php echo get_option('aframe_sign_type_2_frame_color1_p_side_1_cost_10'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color1_p_side_1_cost_11"  value="<?php echo get_option('aframe_sign_type_2_frame_color1_p_side_1_cost_11'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color1_p_side_1_cost_12"  value="<?php echo get_option('aframe_sign_type_2_frame_color1_p_side_1_cost_12'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color1_p_side_1_cost_20"  value="<?php echo get_option('aframe_sign_type_2_frame_color1_p_side_1_cost_20'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color1_p_side_1_cost_25"  value="<?php echo get_option('aframe_sign_type_2_frame_color1_p_side_1_cost_25'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color1_p_side_1_cost_30"  value="<?php echo get_option('aframe_sign_type_2_frame_color1_p_side_1_cost_30'); ?>"/></td>

</tr>
<tr>
<td>Black </td><td>Standard (with Adhesive Signs)</td><td>One Sided</td><td><input type="text" name="aframe_sign_type_1_frame_color2_p_side_1_cost_1"  value="<?php echo get_option('aframe_sign_type_1_frame_color2_p_side_1_cost_1'); ?>" /></td><td><input type="text" name="aframe_sign_type_1_frame_color2_p_side_1_cost_2"  value="<?php echo get_option('aframe_sign_type_1_frame_color2_p_side_1_cost_2'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color2_p_side_1_cost_3"  value="<?php echo get_option('aframe_sign_type_1_frame_color2_p_side_1_cost_3'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color2_p_side_1_cost_4"  value="<?php echo get_option('aframe_sign_type_1_frame_color2_p_side_1_cost_4'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color2_p_side_1_cost_5"  value="<?php echo get_option('aframe_sign_type_1_frame_color2_p_side_1_cost_5'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color2_p_side_1_cost_6"  value="<?php echo get_option('aframe_sign_type_1_frame_color2_p_side_1_cost_6'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color2_p_side_1_cost_7"  value="<?php echo get_option('aframe_sign_type_1_frame_color2_p_side_1_cost_7'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color2_p_side_1_cost_8"  value="<?php echo get_option('aframe_sign_type_1_frame_color2_p_side_1_cost_8'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color2_p_side_1_cost_9"  value="<?php echo get_option('aframe_sign_type_1_frame_color2_p_side_1_cost_9'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color2_p_side_1_cost_10"  value="<?php echo get_option('aframe_sign_type_1_frame_color2_p_side_1_cost_10'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color2_p_side_1_cost_11"  value="<?php echo get_option('aframe_sign_type_1_frame_color2_p_side_1_cost_11'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color2_p_side_1_cost_12"  value="<?php echo get_option('aframe_sign_type_1_frame_color2_p_side_1_cost_12'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color2_p_side_1_cost_20"  value="<?php echo get_option('aframe_sign_type_1_frame_color2_p_side_1_cost_20'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color2_p_side_1_cost_25"  value="<?php echo get_option('aframe_sign_type_1_frame_color2_p_side_1_cost_25'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color2_p_side_1_cost_30"  value="<?php echo get_option('aframe_sign_type_1_frame_color2_p_side_1_cost_30'); ?>"/></td>

</tr>
<tr>
<td>Black </td><td>Standard (with Adhesive Signs)Delux (With Inserted Signs)</td><td>One Sided</td><td><input type="text" name="aframe_sign_type_2_frame_color2_p_side_1_cost_1"  value="<?php echo get_option('aframe_sign_type_2_frame_color2_p_side_1_cost_1'); ?>" /></td><td><input type="text" name="aframe_sign_type_2_frame_color2_p_side_1_cost_2"  value="<?php echo get_option('aframe_sign_type_2_frame_color2_p_side_1_cost_2'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color2_p_side_1_cost_3"  value="<?php echo get_option('aframe_sign_type_2_frame_color2_p_side_1_cost_3'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color2_p_side_1_cost_4"  value="<?php echo get_option('aframe_sign_type_2_frame_color2_p_side_1_cost_4'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color2_p_side_1_cost_5"  value="<?php echo get_option('aframe_sign_type_2_frame_color2_p_side_1_cost_5'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color2_p_side_1_cost_6"  value="<?php echo get_option('aframe_sign_type_2_frame_color2_p_side_1_cost_6'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color2_p_side_1_cost_7"  value="<?php echo get_option('aframe_sign_type_2_frame_color2_p_side_1_cost_7'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color2_p_side_1_cost_8"  value="<?php echo get_option('aframe_sign_type_2_frame_color2_p_side_1_cost_8'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color2_p_side_1_cost_9"  value="<?php echo get_option('aframe_sign_type_2_frame_color2_p_side_1_cost_9'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color2_p_side_1_cost_10"  value="<?php echo get_option('aframe_sign_type_2_frame_color2_p_side_1_cost_10'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color2_p_side_1_cost_11"  value="<?php echo get_option('aframe_sign_type_2_frame_color2_p_side_1_cost_11'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color2_p_side_1_cost_12"  value="<?php echo get_option('aframe_sign_type_2_frame_color2_p_side_1_cost_12'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color2_p_side_1_cost_20"  value="<?php echo get_option('aframe_sign_type_2_frame_color2_p_side_1_cost_20'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color2_p_side_1_cost_25"  value="<?php echo get_option('aframe_sign_type_2_frame_color2_p_side_1_cost_25'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color2_p_side_1_cost_30"  value="<?php echo get_option('aframe_sign_type_2_frame_color2_p_side_1_cost_30'); ?>"/></td>

</tr>
<tr>
<td>White </td><td>Delux (With Inserted Signs)</td><td>Two Sided</td><td><input type="text" name="aframe_sign_type_1_frame_color1_p_side_2_cost_1"  value="<?php echo get_option('aframe_sign_type_1_frame_color1_p_side_2_cost_1'); ?>" /></td><td><input type="text" name="aframe_sign_type_1_frame_color1_p_side_2_cost_2"  value="<?php echo get_option('aframe_sign_type_1_frame_color1_p_side_2_cost_2'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color1_p_side_2_cost_3"  value="<?php echo get_option('aframe_sign_type_1_frame_color1_p_side_2_cost_3'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color1_p_side_2_cost_4"  value="<?php echo get_option('aframe_sign_type_1_frame_color1_p_side_2_cost_4'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color1_p_side_2_cost_5"  value="<?php echo get_option('aframe_sign_type_1_frame_color1_p_side_2_cost_5'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color1_p_side_2_cost_6"  value="<?php echo get_option('aframe_sign_type_1_frame_color1_p_side_2_cost_6'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color1_p_side_2_cost_7"  value="<?php echo get_option('aframe_sign_type_1_frame_color1_p_side_2_cost_7'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color1_p_side_2_cost_8"  value="<?php echo get_option('aframe_sign_type_1_frame_color1_p_side_2_cost_8'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color1_p_side_2_cost_9"  value="<?php echo get_option('aframe_sign_type_1_frame_color1_p_side_2_cost_9'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color1_p_side_2_cost_10"  value="<?php echo get_option('aframe_sign_type_1_frame_color1_p_side_2_cost_10'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color1_p_side_2_cost_11"  value="<?php echo get_option('aframe_sign_type_1_frame_color1_p_side_2_cost_11'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color1_p_side_2_cost_12"  value="<?php echo get_option('aframe_sign_type_1_frame_color1_p_side_2_cost_12'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color1_p_side_2_cost_20"  value="<?php echo get_option('aframe_sign_type_1_frame_color1_p_side_2_cost_20'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color1_p_side_2_cost_25"  value="<?php echo get_option('aframe_sign_type_1_frame_color1_p_side_2_cost_25'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color1_p_side_2_cost_30"  value="<?php echo get_option('aframe_sign_type_1_frame_color1_p_side_2_cost_30'); ?>"/></td>

</tr>
<tr>
<td>White </td><td>Standard (with Adhesive Signs)</td><td>Two Sided</td><td><input type="text" name="aframe_sign_type_2_frame_color1_p_side_2_cost_1"  value="<?php echo get_option('aframe_sign_type_2_frame_color1_p_side_2_cost_1'); ?>" /></td><td><input type="text" name="aframe_sign_type_2_frame_color1_p_side_2_cost_2"  value="<?php echo get_option('aframe_sign_type_2_frame_color1_p_side_2_cost_2'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color1_p_side_2_cost_3"  value="<?php echo get_option('aframe_sign_type_2_frame_color1_p_side_2_cost_3'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color1_p_side_2_cost_4"  value="<?php echo get_option('aframe_sign_type_2_frame_color1_p_side_2_cost_4'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color1_p_side_2_cost_5"  value="<?php echo get_option('aframe_sign_type_2_frame_color1_p_side_2_cost_5'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color1_p_side_2_cost_6"  value="<?php echo get_option('aframe_sign_type_2_frame_color1_p_side_2_cost_6'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color1_p_side_2_cost_7"  value="<?php echo get_option('aframe_sign_type_2_frame_color1_p_side_2_cost_7'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color1_p_side_2_cost_8"  value="<?php echo get_option('aframe_sign_type_2_frame_color1_p_side_2_cost_8'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color1_p_side_2_cost_9"  value="<?php echo get_option('aframe_sign_type_2_frame_color1_p_side_2_cost_9'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color1_p_side_2_cost_10"  value="<?php echo get_option('aframe_sign_type_2_frame_color1_p_side_2_cost_10'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color1_p_side_2_cost_11"  value="<?php echo get_option('aframe_sign_type_2_frame_color1_p_side_2_cost_11'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color1_p_side_2_cost_12"  value="<?php echo get_option('aframe_sign_type_2_frame_color1_p_side_2_cost_12'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color1_p_side_2_cost_20"  value="<?php echo get_option('aframe_sign_type_2_frame_color1_p_side_2_cost_20'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color1_p_side_2_cost_25"  value="<?php echo get_option('aframe_sign_type_2_frame_color1_p_side_2_cost_25'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color1_p_side_2_cost_30"  value="<?php echo get_option('aframe_sign_type_2_frame_color1_p_side_2_cost_30'); ?>"/></td>

</tr>
<tr>
<td>Black </td><td>Delux (With Inserted Signs)</td><td>Two Sided</td><td><input type="text" name="aframe_sign_type_1_frame_color2_p_side_2_cost_1"  value="<?php echo get_option('aframe_sign_type_1_frame_color2_p_side_2_cost_1'); ?>" /></td><td><input type="text" name="aframe_sign_type_1_frame_color2_p_side_2_cost_2"  value="<?php echo get_option('aframe_sign_type_1_frame_color2_p_side_2_cost_2'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color2_p_side_2_cost_3"  value="<?php echo get_option('aframe_sign_type_1_frame_color2_p_side_2_cost_3'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color2_p_side_2_cost_4"  value="<?php echo get_option('aframe_sign_type_1_frame_color2_p_side_2_cost_4'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color2_p_side_2_cost_5"  value="<?php echo get_option('aframe_sign_type_1_frame_color2_p_side_2_cost_5'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color2_p_side_2_cost_6"  value="<?php echo get_option('aframe_sign_type_1_frame_color2_p_side_2_cost_6'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color2_p_side_2_cost_7"  value="<?php echo get_option('aframe_sign_type_1_frame_color2_p_side_2_cost_7'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color2_p_side_2_cost_8"  value="<?php echo get_option('aframe_sign_type_1_frame_color2_p_side_2_cost_8'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color2_p_side_2_cost_9"  value="<?php echo get_option('aframe_sign_type_1_frame_color2_p_side_2_cost_9'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color2_p_side_2_cost_10"  value="<?php echo get_option('aframe_sign_type_1_frame_color2_p_side_2_cost_10'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color2_p_side_2_cost_11"  value="<?php echo get_option('aframe_sign_type_1_frame_color2_p_side_2_cost_11'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color2_p_side_2_cost_12"  value="<?php echo get_option('aframe_sign_type_1_frame_color2_p_side_2_cost_12'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color2_p_side_2_cost_20"  value="<?php echo get_option('aframe_sign_type_1_frame_color2_p_side_2_cost_20'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color2_p_side_2_cost_25"  value="<?php echo get_option('aframe_sign_type_1_frame_color2_p_side_2_cost_25'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color2_p_side_2_cost_30"  value="<?php echo get_option('aframe_sign_type_1_frame_color2_p_side_2_cost_30'); ?>"/></td>

</tr>
<tr>
<td>Black </td><td>Standard (with Adhesive Signs)</td><td>Two Sided</td><td><input type="text" name="aframe_sign_type_2_frame_color2_p_side_2_cost_1"  value="<?php echo get_option('aframe_sign_type_2_frame_color2_p_side_2_cost_1'); ?>" /></td><td><input type="text" name="aframe_sign_type_2_frame_color2_p_side_2_cost_2"  value="<?php echo get_option('aframe_sign_type_2_frame_color2_p_side_2_cost_2'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color2_p_side_2_cost_3"  value="<?php echo get_option('aframe_sign_type_2_frame_color2_p_side_2_cost_3'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color2_p_side_2_cost_4"  value="<?php echo get_option('aframe_sign_type_2_frame_color2_p_side_2_cost_4'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color2_p_side_2_cost_5"  value="<?php echo get_option('aframe_sign_type_2_frame_color2_p_side_2_cost_5'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color2_p_side_2_cost_6"  value="<?php echo get_option('aframe_sign_type_2_frame_color2_p_side_2_cost_6'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color2_p_side_2_cost_7"  value="<?php echo get_option('aframe_sign_type_2_frame_color2_p_side_2_cost_7'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color2_p_side_2_cost_8"  value="<?php echo get_option('aframe_sign_type_2_frame_color2_p_side_2_cost_8'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color2_p_side_2_cost_9"  value="<?php echo get_option('aframe_sign_type_2_frame_color2_p_side_2_cost_9'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color2_p_side_2_cost_10"  value="<?php echo get_option('aframe_sign_type_2_frame_color2_p_side_2_cost_10'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color2_p_side_2_cost_11"  value="<?php echo get_option('aframe_sign_type_2_frame_color2_p_side_2_cost_11'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color2_p_side_2_cost_12"  value="<?php echo get_option('aframe_sign_type_2_frame_color2_p_side_2_cost_12'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color2_p_side_2_cost_20"  value="<?php echo get_option('aframe_sign_type_2_frame_color2_p_side_2_cost_20'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color2_p_side_2_cost_25"  value="<?php echo get_option('aframe_sign_type_2_frame_color2_p_side_2_cost_25'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color2_p_side_2_cost_30"  value="<?php echo get_option('aframe_sign_type_2_frame_color2_p_side_2_cost_30'); ?>"/></td>

</tr>



</tr>
</TABLE>
<p><h1 class='title'> A Frame SIGNS | Frame:   No Frame (Printed Sign(s) Only) | Size:  24" * 36"</h1>

<table class='table table-striped'>


<tr style='text-align:center'>

<td width="100%">Color</td><td>Sign Type</td><td>Printed Side
</td><td>1</td><td>2</td><td>3</td><td>4</td><td>5</td><td>6</td><td>7</td><td>8</td><td>9</td><td>10</td><td>11</td><td>12</td><td>20</td><td>25</td><td>30</td>

</tr>
<tr>
<td>White </td><td>Standard (With Adhesive Signs)</td><td>One Sided</td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_1_cost_1"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_1_cost_1'); ?>" /></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_1_cost_2"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_1_cost_2'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_1_cost_3"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_1_cost_3'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_1_cost_4"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_1_cost_4'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_1_cost_5"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_1_cost_5'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_1_cost_6"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_1_cost_6'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_1_cost_7"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_1_cost_7'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_1_cost_8"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_1_cost_8'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_1_cost_9"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_1_cost_9'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_1_cost_10"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_1_cost_10'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_1_cost_11"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_1_cost_11'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_1_cost_12"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_1_cost_12'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_1_cost_20"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_1_cost_20'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_1_cost_25"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_1_cost_25'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_1_cost_30"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_1_cost_30'); ?>"/></td>

</tr>
<tr>
<td>White </td><td>Standard (With Adhesive Signs)</td><td>One Sided</td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_1_cost_1"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_1_cost_1'); ?>" /></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_1_cost_2"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_1_cost_2'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_1_cost_3"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_1_cost_3'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_1_cost_4"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_1_cost_4'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_1_cost_5"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_1_cost_5'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_1_cost_6"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_1_cost_6'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_1_cost_7"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_1_cost_7'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_1_cost_8"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_1_cost_8'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_1_cost_9"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_1_cost_9'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_1_cost_10"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_1_cost_10'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_1_cost_11"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_1_cost_11'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_1_cost_12"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_1_cost_12'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_1_cost_20"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_1_cost_20'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_1_cost_25"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_1_cost_25'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_1_cost_30"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_1_cost_30'); ?>"/></td>

</tr>
<tr>
<td>Black </td><td>Delux (With Inserted Signs)</td><td>One Sided</td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_1_cost_1"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_1_cost_1'); ?>" /></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_1_cost_2"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_1_cost_2'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_1_cost_3"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_1_cost_3'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_1_cost_4"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_1_cost_4'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_1_cost_5"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_1_cost_5'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_1_cost_6"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_1_cost_6'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_1_cost_7"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_1_cost_7'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_1_cost_8"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_1_cost_8'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_1_cost_9"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_1_cost_9'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_1_cost_10"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_1_cost_10'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_1_cost_11"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_1_cost_11'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_1_cost_12"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_1_cost_12'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_1_cost_20"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_1_cost_20'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_1_cost_25"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_1_cost_25'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_1_cost_30"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_1_cost_30'); ?>"/></td>

</tr>
<tr>
<td>Black </td><td>Delux (With Inserted Signs)</td><td>One Sided</td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_1_cost_1"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_1_cost_1'); ?>" /></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_1_cost_2"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_1_cost_2'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_1_cost_3"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_1_cost_3'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_1_cost_4"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_1_cost_4'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_1_cost_5"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_1_cost_5'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_1_cost_6"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_1_cost_6'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_1_cost_7"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_1_cost_7'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_1_cost_8"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_1_cost_8'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_1_cost_9"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_1_cost_9'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_1_cost_10"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_1_cost_10'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_1_cost_11"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_1_cost_11'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_1_cost_12"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_1_cost_12'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_1_cost_20"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_1_cost_20'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_1_cost_25"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_1_cost_25'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_1_cost_30"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_1_cost_30'); ?>"/></td>

</tr>
<tr>
<td>White </td><td>Delux (With Inserted Signs)</td><td>Two Sided</td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_2_cost_1"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_2_cost_1'); ?>" /></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_2_cost_2"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_2_cost_2'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_2_cost_3"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_2_cost_3'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_2_cost_4"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_2_cost_4'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_2_cost_5"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_2_cost_5'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_2_cost_6"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_2_cost_6'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_2_cost_7"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_2_cost_7'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_2_cost_8"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_2_cost_8'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_2_cost_9"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_2_cost_9'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_2_cost_10"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_2_cost_10'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_2_cost_11"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_2_cost_11'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_2_cost_12"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_2_cost_12'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_2_cost_20"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_2_cost_20'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_2_cost_25"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_2_cost_25'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_2_cost_30"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_2_cost_30'); ?>"/></td>

</tr>
<tr>
<td>White </td><td>Delux (With Inserted Signs)</td><td>Two Sided</td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_2_cost_1"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_2_cost_1'); ?>" /></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_2_cost_2"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_2_cost_2'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_2_cost_3"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_2_cost_3'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_2_cost_4"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_2_cost_4'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_2_cost_5"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_2_cost_5'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_2_cost_6"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_2_cost_6'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_2_cost_7"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_2_cost_7'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_2_cost_8"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_2_cost_8'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_2_cost_9"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_2_cost_9'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_2_cost_10"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_2_cost_10'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_2_cost_11"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_2_cost_11'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_2_cost_12"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_2_cost_12'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_2_cost_20"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_2_cost_20'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_2_cost_25"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_2_cost_25'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_2_cost_30"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_2_cost_30'); ?>"/></td>

</tr>
<tr>
<td>Black </td><td>Delux (With Inserted Signs)</td><td>Two Sided</td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_2_cost_1"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_2_cost_1'); ?>" /></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_2_cost_2"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_2_cost_2'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_2_cost_3"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_2_cost_3'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_2_cost_4"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_2_cost_4'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_2_cost_5"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_2_cost_5'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_2_cost_6"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_2_cost_6'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_2_cost_7"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_2_cost_7'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_2_cost_8"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_2_cost_8'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_2_cost_9"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_2_cost_9'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_2_cost_10"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_2_cost_10'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_2_cost_11"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_2_cost_11'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_2_cost_12"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_2_cost_12'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_2_cost_20"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_2_cost_20'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_2_cost_25"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_2_cost_25'); ?>"/></td><td><input type="text" name="aframe_sign_type_1_frame_color0_p_side_2_cost_30"  value="<?php echo get_option('aframe_sign_type_1_frame_color0_p_side_2_cost_30'); ?>"/></td>

</tr>
<tr>
<td>Black </td><td>Delux (With Inserted Signs)</td><td>Two Sided</td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_2_cost_1"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_2_cost_1'); ?>" /></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_2_cost_2"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_2_cost_2'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_2_cost_3"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_2_cost_3'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_2_cost_4"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_2_cost_4'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_2_cost_5"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_2_cost_5'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_2_cost_6"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_2_cost_6'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_2_cost_7"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_2_cost_7'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_2_cost_8"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_2_cost_8'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_2_cost_9"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_2_cost_9'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_2_cost_10"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_2_cost_10'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_2_cost_11"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_2_cost_11'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_2_cost_12"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_2_cost_12'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_2_cost_20"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_2_cost_20'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_2_cost_25"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_2_cost_25'); ?>"/></td><td><input type="text" name="aframe_sign_type_2_frame_color0_p_side_2_cost_30"  value="<?php echo get_option('aframe_sign_type_2_frame_color0_p_side_2_cost_30'); ?>"/></td>

</tr>



</tr>

</table>

<p><input type="submit" name="Submit" value="Update" /></p>
	<input type="hidden" name="action" value="update" />
<input type="hidden" name="page_options" value="aframe_sign_type_1_frame_color1_p_side_1_cost_1,aframe_sign_type_1_frame_color1_p_side_1_cost_2,aframe_sign_type_1_frame_color1_p_side_1_cost_3,aframe_sign_type_1_frame_color1_p_side_1_cost_4,aframe_sign_type_1_frame_color1_p_side_1_cost_5,aframe_sign_type_1_frame_color1_p_side_1_cost_6,aframe_sign_type_1_frame_color1_p_side_1_cost_7,aframe_sign_type_1_frame_color1_p_side_1_cost_8,aframe_sign_type_1_frame_color1_p_side_1_cost_9,aframe_sign_type_1_frame_color1_p_side_1_cost_10,aframe_sign_type_1_frame_color1_p_side_1_cost_11,aframe_sign_type_1_frame_color1_p_side_1_cost_12,aframe_sign_type_1_frame_color1_p_side_1_cost_20,aframe_sign_type_1_frame_color1_p_side_1_cost_25,aframe_sign_type_1_frame_color1_p_side_1_cost_30,aframe_sign_type_2_frame_color1_p_side_1_cost_1,aframe_sign_type_2_frame_color1_p_side_1_cost_2,aframe_sign_type_2_frame_color1_p_side_1_cost_3,aframe_sign_type_2_frame_color1_p_side_1_cost_4,aframe_sign_type_2_frame_color1_p_side_1_cost_5,aframe_sign_type_2_frame_color1_p_side_1_cost_6,aframe_sign_type_2_frame_color1_p_side_1_cost_7,aframe_sign_type_2_frame_color1_p_side_1_cost_8,aframe_sign_type_2_frame_color1_p_side_1_cost_9,aframe_sign_type_2_frame_color1_p_side_1_cost_10,aframe_sign_type_2_frame_color1_p_side_1_cost_11,aframe_sign_type_2_frame_color1_p_side_1_cost_12,aframe_sign_type_2_frame_color1_p_side_1_cost_20,aframe_sign_type_2_frame_color1_p_side_1_cost_25,aframe_sign_type_2_frame_color1_p_side_1_cost_30,aframe_sign_type_1_frame_color2_p_side_1_cost_1,aframe_sign_type_1_frame_color2_p_side_1_cost_2,aframe_sign_type_1_frame_color2_p_side_1_cost_3,aframe_sign_type_1_frame_color2_p_side_1_cost_4,aframe_sign_type_1_frame_color2_p_side_1_cost_5,aframe_sign_type_1_frame_color2_p_side_1_cost_6,aframe_sign_type_1_frame_color2_p_side_1_cost_7,aframe_sign_type_1_frame_color2_p_side_1_cost_8,aframe_sign_type_1_frame_color2_p_side_1_cost_9,aframe_sign_type_1_frame_color2_p_side_1_cost_10,aframe_sign_type_1_frame_color2_p_side_1_cost_11,aframe_sign_type_1_frame_color2_p_side_1_cost_12,aframe_sign_type_1_frame_color2_p_side_1_cost_20,aframe_sign_type_1_frame_color2_p_side_1_cost_25,aframe_sign_type_1_frame_color2_p_side_1_cost_30,
aframe_sign_type_2_frame_color2_p_side_1_cost_1,aframe_sign_type_2_frame_color2_p_side_1_cost_2,aframe_sign_type_2_frame_color2_p_side_1_cost_3,aframe_sign_type_2_frame_color2_p_side_1_cost_4,aframe_sign_type_2_frame_color2_p_side_1_cost_5,aframe_sign_type_2_frame_color2_p_side_1_cost_6,aframe_sign_type_2_frame_color2_p_side_1_cost_7,aframe_sign_type_2_frame_color2_p_side_1_cost_8,aframe_sign_type_2_frame_color2_p_side_1_cost_9,aframe_sign_type_2_frame_color2_p_side_1_cost_10,aframe_sign_type_2_frame_color2_p_side_1_cost_11,aframe_sign_type_2_frame_color2_p_side_1_cost_12,aframe_sign_type_2_frame_color2_p_side_1_cost_20,aframe_sign_type_2_frame_color2_p_side_1_cost_25,aframe_sign_type_2_frame_color2_p_side_1_cost_30,aframe_sign_type_1_frame_color1_p_side_2_cost_1,aframe_sign_type_1_frame_color1_p_side_2_cost_2,aframe_sign_type_1_frame_color1_p_side_2_cost_3,aframe_sign_type_1_frame_color1_p_side_2_cost_4,aframe_sign_type_1_frame_color1_p_side_2_cost_5,aframe_sign_type_1_frame_color1_p_side_2_cost_6,aframe_sign_type_1_frame_color1_p_side_2_cost_7,aframe_sign_type_1_frame_color1_p_side_2_cost_8,aframe_sign_type_1_frame_color1_p_side_2_cost_9,aframe_sign_type_1_frame_color1_p_side_2_cost_10,aframe_sign_type_1_frame_color1_p_side_2_cost_11,aframe_sign_type_1_frame_color1_p_side_2_cost_12,aframe_sign_type_1_frame_color1_p_side_2_cost_20,aframe_sign_type_1_frame_color1_p_side_2_cost_25,aframe_sign_type_1_frame_color1_p_side_2_cost_30,aframe_sign_type_2_frame_color1_p_side_2_cost_1,aframe_sign_type_2_frame_color1_p_side_2_cost_2,aframe_sign_type_2_frame_color1_p_side_2_cost_3,aframe_sign_type_2_frame_color1_p_side_2_cost_4,aframe_sign_type_2_frame_color1_p_side_2_cost_5,aframe_sign_type_2_frame_color1_p_side_2_cost_6,aframe_sign_type_2_frame_color1_p_side_2_cost_7,aframe_sign_type_2_frame_color1_p_side_2_cost_8,aframe_sign_type_2_frame_color1_p_side_2_cost_9,aframe_sign_type_2_frame_color1_p_side_2_cost_10,aframe_sign_type_2_frame_color1_p_side_2_cost_11,aframe_sign_type_2_frame_color1_p_side_2_cost_12,aframe_sign_type_2_frame_color1_p_side_2_cost_20,aframe_sign_type_2_frame_color1_p_side_2_cost_25,aframe_sign_type_2_frame_color1_p_side_2_cost_30,aframe_sign_type_1_frame_color2_p_side_2_cost_1,aframe_sign_type_1_frame_color2_p_side_2_cost_2,aframe_sign_type_1_frame_color2_p_side_2_cost_3,aframe_sign_type_1_frame_color2_p_side_2_cost_4,aframe_sign_type_1_frame_color2_p_side_2_cost_5,aframe_sign_type_1_frame_color2_p_side_2_cost_6,aframe_sign_type_1_frame_color2_p_side_2_cost_7,aframe_sign_type_1_frame_color2_p_side_2_cost_8,aframe_sign_type_1_frame_color2_p_side_2_cost_9,aframe_sign_type_1_frame_color2_p_side_2_cost_10,aframe_sign_type_1_frame_color2_p_side_2_cost_11,aframe_sign_type_1_frame_color2_p_side_2_cost_12,aframe_sign_type_1_frame_color2_p_side_2_cost_20,aframe_sign_type_1_frame_color2_p_side_2_cost_25,aframe_sign_type_1_frame_color2_p_side_2_cost_30,
aframe_sign_type_2_frame_color2_p_side_2_cost_1,aframe_sign_type_2_frame_color2_p_side_2_cost_2,aframe_sign_type_2_frame_color2_p_side_2_cost_3,aframe_sign_type_2_frame_color2_p_side_2_cost_4,aframe_sign_type_2_frame_color2_p_side_2_cost_5,aframe_sign_type_2_frame_color2_p_side_2_cost_6,aframe_sign_type_2_frame_color2_p_side_2_cost_7,aframe_sign_type_2_frame_color2_p_side_2_cost_8,aframe_sign_type_2_frame_color2_p_side_2_cost_9,aframe_sign_type_2_frame_color2_p_side_2_cost_10,aframe_sign_type_2_frame_color2_p_side_2_cost_11,aframe_sign_type_2_frame_color2_p_side_2_cost_12,aframe_sign_type_2_frame_color2_p_side_2_cost_20,aframe_sign_type_2_frame_color2_p_side_2_cost_25,aframe_sign_type_2_frame_color2_p_side_2_cost_30,aframe_sign_type_1_frame_color0_p_side_1_cost_1,aframe_sign_type_1_frame_color0_p_side_1_cost_2,aframe_sign_type_1_frame_color0_p_side_1_cost_3,aframe_sign_type_1_frame_color0_p_side_1_cost_4,aframe_sign_type_1_frame_color0_p_side_1_cost_5,aframe_sign_type_1_frame_color0_p_side_1_cost_6,aframe_sign_type_1_frame_color0_p_side_1_cost_7,aframe_sign_type_1_frame_color0_p_side_1_cost_8,aframe_sign_type_1_frame_color0_p_side_1_cost_9,aframe_sign_type_1_frame_color0_p_side_1_cost_10,aframe_sign_type_1_frame_color0_p_side_1_cost_11,aframe_sign_type_1_frame_color0_p_side_1_cost_12,aframe_sign_type_1_frame_color0_p_side_1_cost_20,aframe_sign_type_1_frame_color0_p_side_1_cost_25,aframe_sign_type_1_frame_color0_p_side_1_cost_30,aframe_sign_type_2_frame_color0_p_side_1_cost_1,aframe_sign_type_2_frame_color0_p_side_1_cost_2,aframe_sign_type_2_frame_color0_p_side_1_cost_3,aframe_sign_type_2_frame_color0_p_side_1_cost_4,aframe_sign_type_2_frame_color0_p_side_1_cost_5,aframe_sign_type_2_frame_color0_p_side_1_cost_6,aframe_sign_type_2_frame_color0_p_side_1_cost_7,aframe_sign_type_2_frame_color0_p_side_1_cost_8,aframe_sign_type_2_frame_color0_p_side_1_cost_9,aframe_sign_type_2_frame_color0_p_side_1_cost_10,aframe_sign_type_2_frame_color0_p_side_1_cost_11,aframe_sign_type_2_frame_color0_p_side_1_cost_12,aframe_sign_type_2_frame_color0_p_side_1_cost_20,aframe_sign_type_2_frame_color0_p_side_1_cost_25,aframe_sign_type_2_frame_color0_p_side_1_cost_30,aframe_sign_type_1_frame_color0_p_side_1_cost_1,aframe_sign_type_1_frame_color0_p_side_1_cost_2,aframe_sign_type_1_frame_color0_p_side_1_cost_3,aframe_sign_type_1_frame_color0_p_side_1_cost_4,aframe_sign_type_1_frame_color0_p_side_1_cost_5,aframe_sign_type_1_frame_color0_p_side_1_cost_6,aframe_sign_type_1_frame_color0_p_side_1_cost_7,aframe_sign_type_1_frame_color0_p_side_1_cost_8,aframe_sign_type_1_frame_color0_p_side_1_cost_9,aframe_sign_type_1_frame_color0_p_side_1_cost_10,aframe_sign_type_1_frame_color0_p_side_1_cost_11,aframe_sign_type_1_frame_color0_p_side_1_cost_12,aframe_sign_type_1_frame_color0_p_side_1_cost_20,aframe_sign_type_1_frame_color0_p_side_1_cost_25,aframe_sign_type_1_frame_color0_p_side_1_cost_30,
aframe_sign_type_2_frame_color0_p_side_1_cost_1,aframe_sign_type_2_frame_color0_p_side_1_cost_2,aframe_sign_type_2_frame_color0_p_side_1_cost_3,aframe_sign_type_2_frame_color0_p_side_1_cost_4,aframe_sign_type_2_frame_color0_p_side_1_cost_5,aframe_sign_type_2_frame_color0_p_side_1_cost_6,aframe_sign_type_2_frame_color0_p_side_1_cost_7,aframe_sign_type_2_frame_color0_p_side_1_cost_8,aframe_sign_type_2_frame_color0_p_side_1_cost_9,aframe_sign_type_2_frame_color0_p_side_1_cost_10,aframe_sign_type_2_frame_color0_p_side_1_cost_11,aframe_sign_type_2_frame_color0_p_side_1_cost_12,aframe_sign_type_2_frame_color0_p_side_1_cost_20,aframe_sign_type_2_frame_color0_p_side_1_cost_25,aframe_sign_type_2_frame_color0_p_side_1_cost_30,aframe_sign_type_1_frame_color0_p_side_2_cost_1,aframe_sign_type_1_frame_color0_p_side_2_cost_2,aframe_sign_type_1_frame_color0_p_side_2_cost_3,aframe_sign_type_1_frame_color0_p_side_2_cost_4,aframe_sign_type_1_frame_color0_p_side_2_cost_5,aframe_sign_type_1_frame_color0_p_side_2_cost_6,aframe_sign_type_1_frame_color0_p_side_2_cost_7,aframe_sign_type_1_frame_color0_p_side_2_cost_8,aframe_sign_type_1_frame_color0_p_side_2_cost_9,aframe_sign_type_1_frame_color0_p_side_2_cost_10,aframe_sign_type_1_frame_color0_p_side_2_cost_11,aframe_sign_type_1_frame_color0_p_side_2_cost_12,aframe_sign_type_1_frame_color0_p_side_2_cost_20,aframe_sign_type_1_frame_color0_p_side_2_cost_25,aframe_sign_type_1_frame_color0_p_side_2_cost_30,aframe_sign_type_2_frame_color0_p_side_2_cost_1,aframe_sign_type_2_frame_color0_p_side_2_cost_2,aframe_sign_type_2_frame_color0_p_side_2_cost_3,aframe_sign_type_2_frame_color0_p_side_2_cost_4,aframe_sign_type_2_frame_color0_p_side_2_cost_5,aframe_sign_type_2_frame_color0_p_side_2_cost_6,aframe_sign_type_2_frame_color0_p_side_2_cost_7,aframe_sign_type_2_frame_color0_p_side_2_cost_8,aframe_sign_type_2_frame_color0_p_side_2_cost_9,aframe_sign_type_2_frame_color0_p_side_2_cost_10,aframe_sign_type_2_frame_color0_p_side_2_cost_11,aframe_sign_type_2_frame_color0_p_side_2_cost_12,aframe_sign_type_2_frame_color0_p_side_2_cost_20,aframe_sign_type_2_frame_color0_p_side_2_cost_25,aframe_sign_type_2_frame_color0_p_side_2_cost_30,aframe_sign_type_1_frame_color0_p_side_2_cost_1,aframe_sign_type_1_frame_color0_p_side_2_cost_2,aframe_sign_type_1_frame_color0_p_side_2_cost_3,aframe_sign_type_1_frame_color0_p_side_2_cost_4,aframe_sign_type_1_frame_color0_p_side_2_cost_5,aframe_sign_type_1_frame_color0_p_side_2_cost_6,aframe_sign_type_1_frame_color0_p_side_2_cost_7,aframe_sign_type_1_frame_color0_p_side_2_cost_8,aframe_sign_type_1_frame_color0_p_side_2_cost_9,aframe_sign_type_1_frame_color0_p_side_2_cost_10,aframe_sign_type_1_frame_color0_p_side_2_cost_11,aframe_sign_type_1_frame_color0_p_side_2_cost_12,aframe_sign_type_1_frame_color0_p_side_2_cost_20,aframe_sign_type_1_frame_color0_p_side_2_cost_25,aframe_sign_type_1_frame_color0_p_side_2_cost_30,
aframe_sign_type_2_frame_color0_p_side_2_cost_1,aframe_sign_type_2_frame_color0_p_side_2_cost_2,aframe_sign_type_2_frame_color0_p_side_2_cost_3,aframe_sign_type_2_frame_color0_p_side_2_cost_4,aframe_sign_type_2_frame_color0_p_side_2_cost_5,aframe_sign_type_2_frame_color0_p_side_2_cost_6,aframe_sign_type_2_frame_color0_p_side_2_cost_7,aframe_sign_type_2_frame_color0_p_side_2_cost_8,aframe_sign_type_2_frame_color0_p_side_2_cost_9,aframe_sign_type_2_frame_color0_p_side_2_cost_10,aframe_sign_type_2_frame_color0_p_side_2_cost_11,aframe_sign_type_2_frame_color0_p_side_2_cost_12,aframe_sign_type_2_frame_color0_p_side_2_cost_20,aframe_sign_type_2_frame_color0_p_side_2_cost_25,aframe_sign_type_2_frame_color0_p_side_2_cost_30,">
</div>
</form>